name: Deploy Java App to Elastic Beanstalk via S3

on:
  push:
    branches: [ main ] 

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v4
    
    # Setup Java environment
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'
        cache: 'maven'
    
    # Build the application
    - name: Build with Maven
      run: mvn clean package -DskipTests
    
    # Optional: Run tests
    #- name: Run tests
    #  run: mvn test
    
    # Create deployment package
    - name: Create deployment package
      run: |
        mkdir deployment
        # Adjust the source JAR path based on your Maven project structure
        cp target/*.jar deployment/application.jar
        
        # Create a deployment zip that includes the JAR and Elastic Beanstalk config if needed
        cd deployment
        zip -r application.zip .
    
    - name: Verify deployment package
      run: ls -lh deployment
    
    # Configure AWS credentials
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    
    # Upload to S3 Bucket
    - name: Upload to S3
      run: |
        aws s3 cp deployment/application.zip s3://${{ secrets.S3_BUCKET_NAME }}
    
    # Deploy to Elastic Beanstalk
    - name: Deploy to Elastic Beanstalk
      run: |
        aws elasticbeanstalk create-application-version \
          --application-name elastic-bean-stalk-application \
          --version-label ${{ github.sha }} \
          --source-bundle "S3Bucket=${{ secrets.S3_BUCKET_NAME }},S3Key=application.zip"
    
        aws elasticbeanstalk update-environment \
          --environment-name Elastic-bean-stalk-application-env-5 \
          --version-label ${{ github.sha }}
